= Immutable CI

== Summary

This project aims at describing our CI using jenkins DSL Plugin.

It starts Jenkins with Git and DSL Plugins, fetch a git repository to retrieve
the DSL configuration and finally make sure this DSL is run at start and
on every changes.

That way, you just have to write your jobs in `build-script` file and
your jenkins or any future jenkins will make them run.

== How to use it

=== Key container

We want our TLS keys to be in an other container. This allows us to publish our
 Jenkins stateless container, and to be able to easily change the TLS keys. 
Jenkins container will use the --volumes-from when run to access certificates.

 - First put your TLS keys in the $PWD/keys folder

You are expected to provide :

 - ca.pem : The CA of your server certificate
 - cert.pem : Your client certificate
 - key.pem : The key used to generate client certificate

To construct the key holding container :

----
$docker build -f DockerFileKeyContainer -t keys .
$docker run -v /keys --name keys keys
----

=== Launch Jenkins

To start a jenkins instance, you need to have a key container on the node you are 
launching jenkins. Then :

----
$docker build --tag myjenkins .
$docker run -p 8080:8080 --volumes-from keys --env JENKINS_URL="MY_JENKINS_URL" --env GITHUB_TOKEN="MY_GITHUB_TOKEN" --env SLACK_TOKEN="MY_SLACK_TOKEN" --env DOCKER_USER="MY_DOCKER_USER" --name jks myjenkins
----

Where:

 - __MY_JENKINS_URL__: is the external URL of your jenkins (ex. "http://ci-james.org:8080/")
 - __MY_GITHUB_TOKEN__: is the token used to access the GitHub API (https://github.com/settings/tokens)
 - __MY_SLACK_TOKEN__: is the token used to access to Slack (https://my.slack.com/services/new/jenkins-ci) +
If not given, the slack plugin will not be enabled.
 - __MY_DOCKER_USER__: is the Docker Hub user used to publish the build, see publishing section (ex. myuser) +
If not given, publishing to Docker Hub will not be enabled.

Then, you can open it in your browser :

----
$firefox http://`docker inspect --format {{.NetworkSettings.IPAddress}} jks`:8080
or
$firefox http://MY_JENKINS_URL
----

=== Publishing to Docker 

This feature is only available when building the *master* branch.

You may want to publish the image produced by the build on a Docker Hub account.
To achieve that, you have to provide a user name to the *docker run* command, +
and fill the *.dockercfg* file located in the root folder of this project.

This file is produced by the *docker login* command (https://docs.docker.com/engine/reference/commandline/login/).

=== Jobs requirements

You need some extra container for the jobs to run well.

==== Cache for maven

We will then add a container for caching maven repositories ( accelerate builds, 
avoid errors on maven failing retrieving its dependencies). You will need it on 
nodes running James compilation through docker.

----
$docker build -f DockerFileMavenCache -t maven-cache .
$docker run -v /root/.m2 --name maven-cache -e affinity:container==keys maven-cache
----

==== James Keystore

If you want to use james deploy script, you need to have a docker container 
with the James TLS certificates. You may not want to publish a container with 
such sensitive content, or even commit it in a source code management system.

First copy James TLS certificate to the directory containing this README. Or you can generate them using :

----
$keytool -genkey -alias james -keyalg RSA -keystore keystore
----

NOTE: To generate James keystore this way, you need to have keytool installed. This tools comes from the JDK.

Be sure that the password you provide matches with James configuration. You will 
find it in james-parent project, in the destination/conf directory. These files are 
'imapserver.xml', 'pop3server.xml' and 'smtpserver.xml'. Edit them locally before 
launching james image build. Default value is set to 'james72laBalle').

Then, run these command to set up this container on nodes that will hosts James servers :

----
$docker build -f DockerfileJamesTlsKeyContainer -t keystore .
$docker run -v /keys --name keystore keystore
----
