= Immutable CI

== Summary

This project aims at describing our CI using jenkins DSL Plugin.

It starts Jenkins with Git and DSL Plugins, fetch a git repository to retrieve
the DSL configuration and finally make sure this DSL is run at start and
on every changes.

That way, you just have to write your jobs in `build-script` file and
your jenkins or any future jenkins will make them run.

== How to use it

We want our TLS keys to be in an other container. This allows us to publish our
 Jenkins stateless container, and to be able to easily change the TLS keys. 
Jenkins container will use the --volumes-from when run to access certificates.

 - First put your TLS keys in the $PWD/keys folder

You are expected to provide :

 - ca.pem : The CA of your server certificate
 - cert.pem : Your client certificate
 - key.pem : The key used to generate client certificate

To construct the key holding container :

----
$docker build -f DockerFileKeyContainer -t keys .
$docker run -v /keys --name keys keys
----

We will then add a container for caching maven repositories ( accelerate builds, 
avoid errors on maven failing retrieving its dependencies ) :

----
$docker build -f DockerFileMavenCache -t maven-cache .
$docker run -v /root/.m2 --name maven-cache -e affinity:container==keys maven-cache
----

To start a jenkins instance, you now just have to do :

----
$docker build --tag myjenkins .
$docker run -p 8080:8080 --volumes-from keys --name jks myjenkins
----

Then, you can open it in your browser :

----
$firefox http://`docker inspect --format {{.NetworkSettings.IPAddress}} jks`:8080
----

Note : If you want to use james deploy script, you need to have a docker container 
with the James TLS certificates. 

First copy James TLS certificate to this directory. Or you can generate them using :

----
$keytool -genkey -alias james -keyalg RSA -keystore keystore
----

Be sure that the password you provide matches with James configuration.

Run these command to set up this container on nodes that will hosts James servers :

----
$docker build -f DockerfileJamesTlsKeyContainer -t keystore .
$docker run -v /keys --name keystore keystore
----
